workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    environment:
      # ios_signing:
      #   distribution_type: app_store
      #   bundle_identifier: io.codemagic.fluttersample
      # vars:
      #   APP_STORE_APPLE_ID: 1555555551
      flutter: 3.24.5
    scripts:
      - name: Get Flutter packages
        script: |
          cd ./mobile
          flutter pub get
      - name: Install pods
        script: |
          cd ./mobile
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter analyze
        script: | 
          cd ./mobile
          flutter analyze
      - name: Flutter unit tests
        script: |
          cd ./mobile
          flutter test
        ignore_failure: true
      - name: Flutter build ipa
        script: |
          cd ./mobile
          flutter build ios --debug --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
      
